MODELS=models
IMAGES=
SEGMENTATION=ey-seg-$(IMAGES)
OCR=ey-ocr-$(IMAGES)
OCRVIS=ey-ocr-vis-$(IMAGES)

dirs:
	mkdir -p "$(SEGMENTATION)"
	ln -r -s "$(IMAGES)" "$(SEGMENTATION)/$(IMAGES)"
	mkdir -p "$(OCR)"
	ln -r -s "$(IMAGES)" "$(OCR)/$(IMAGES)"
	mkdir -p "$(OCRVIS)"
	ln -r -s "$(IMAGES)" "$(OCRVIS)/$(IMAGES)"
layout:
	eynollah layout -m "$(MODELS)" -di "$(IMAGES)" -o "$(SEGMENTATION)" -light -tll -fl
ocr: dirs layout
	eynollah ocr -m "$(MODELS)" -di "$(IMAGES)" -dx "$(SEGMENTATION)" -o "$(OCR)"
	rm -rf "$(OCRVIS)"
ocr-vis: dirs layout
	eynollah ocr -m "$(MODELS)" -di "$(IMAGES)" -dx "$(SEGMENTATION)" -o "$(OCR)" -doit "$(OCRVIS)" -dtoi
